export const FETCHING_WEATHER_REQUEST = 'FETCHING_WEATHER_REQUEST';
export const FETCHING_WEATHER_SUCCESS = 'FETCHING_WEATHER_SUCCESS';
export const FETCHING_WEATHER_FAILURE = 'FETCHING_WEATHER_FAILURE';

export const FETCHING_FORECAST_REQUEST = 'FETCHING_FORECAST_REQUEST';
export const FETCHING_FORECAST_SUCCESS = 'FETCHING_FORECAST_SUCCESS';
export const FETCHING_FORECAST_FAILURE = 'FETCHING_FORECAST_FAILURE';

